PRODUCT_NAME_IN_STOCK_AND_REAL = 'Наименование'
PRODUCT_NAME_IN_REPORT = 'Название SKU'
PRODUCT_COUNT = 'Кол-во'
PRODUCT_SUM = 'Сумма'
CURRENT_BALANCE = 'Тек. Остаток'
SHOP_ADDRESS_COL = 'Адрес т.т. '
TARGET_SHEET_NAME = 'Портянка'
